# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
SandwichIngredient.destroy_all
Ingredient.destroy_all 
Sandwich.destroy_all
User.destroy_all

avacado = Ingredient.create({name: 'Avacado', category: 'protein nonMeat', price: 6.00})
egg_salad = Ingredient.create({name: 'Egg Salad', category: 'protein nonMeat', price: 5.25})
hummus = Ingredient.create({name: 'Hummus', category: 'protein nonMeat', price: 5.00})
portobello_mushroom = Ingredient.create({name: 'Portobello Mushroom', category: 'protein nonMeat', price: 6.25})

corned_beef = Ingredient.create({name: 'Corned Beef', category: 'protein beef', price: 7.95})
grilled_steak = Ingredient.create({name: 'Avacado', category: 'protein beef', price: 8.95})
pastrami = Ingredient.create({name: 'Pastrami', category: 'protein beef', price: 7.95})
roast_beef = Ingredient.create({name: 'Roast Beef', category: 'protein beef', price: 7.95})

chicken_cutlet = Ingredient.create({name: 'Chicken Cutlet (Breaded)', category: 'protein chicken', price: 8.95})
chicken_salad = Ingredient.create({name: 'Chicken Salad', category: 'protein chicken', price: 7.95})
grilled_chicken_breast = Ingredient.create({name: 'Grilled Chicken Breast', category: 'protein chicken', price: 8.95})

blt = Ingredient.create({name: 'BLT', category: 'protein pork', price: 6.25})
capicola = Ingredient.create({name: 'Capicola', category: 'protein pork', price: 7.95})
genoa_salami = Ingredient.create({name: 'Genoa Salami', category: 'protein pork', price: 7.95})
ham = Ingredient.create({name: 'Ham', category: 'protein pork', price: 7.95})
prosciutto = Ingredient.create({name: 'Prosciutto', category: 'protein pork', price: 8.95})
smoked_ham = Ingredient.create({name: 'Smoked Black Forest Ham', category: 'protein pork', price: 7.95})

smoked_turkey = Ingredient.create({name: 'Smoked Turkey', category: 'protein turkey', price: 7.95})
turkey = Ingredient.create({name: 'Turkey', category: 'protein turkey', price: 7.95})
turkey_club = Ingredient.create({name: 'Turkey Club', category: 'protein turkey', price: 10.25})
turkey_pastrami = Ingredient.create({name: 'Turkey Pastrami', category: 'protein turkey', price: 7.95})

smoked_nova = Ingredient.create({name: 'Smoked Turkey', category: 'protein fish', price: 9.25})
tuna = Ingredient.create({name: 'Tuna Salad', category: 'protein fish', price: 7.95})
cod_fish = Ingredient.create({name: 'Fried Cod Fish', category: 'protein fish', price: 8.95})


wheat = Ingredient.create({name: 'Wheat' , category: 'bread', price: 0})
focaccia = Ingredient.create({name: 'Focaccia' , category: 'bread', price: 0})
sourdough = Ingredient.create({name: 'Sourdough' , category: 'bread', price: 0})
white = Ingredient.create({name: 'White' , category: 'bread', price: 0})
brioche = Ingredient.create({name: 'Brioche' , category: 'bread', price: 0})
kaiser_roll = Ingredient.create({name: 'Kaiser Roll', category: 'bread', price: 0})
wrap = Ingredient.create({name: 'Wrap' , category: 'bread', price: 0})
ciabatta = Ingredient.create({name: 'Ciabatta' , category: 'bread', price: 0})
marble_rye = Ingredient.create({name: 'Marble Rye', category: 'bread', price: 0})
spinach_wrap = Ingredient.create({name: 'Spinach Wrap', category: 'bread', price: 0})
club = Ingredient.create({name: 'Club', category: 'bread', price: 0})
pumpernickel = Ingredient.create({name: 'Pumpernickel' , category: 'bread', price: 0})
sundried_tomoato_wrap = Ingredient.create({name: 'Sun Dried Tomato Wrap', category: 'bread', price: 0})
croissant = Ingredient.create({name: 'Croissant' , category: 'bread', price: 0})
rye = Ingredient.create({name: 'Rye' , category: 'bread', price: 0}) 
whole_wheat_wrap = Ingredient.create({name: 'Whole Wheat Wrap', category: 'bread', price: 0})

alpine_cheddar = Ingredient.create({name: 'Alpine Cheddar', category: 'cheese', price: 0.50})
alpine_swiss = Ingredient.create({name: 'Alpine Swiss', category: 'cheese', price: 0.50})
american = Ingredient.create({name: 'American', category: 'cheese', price: 0.50}) 
cheddar = Ingredient.create({name: 'Cheddar' , category: 'cheese', price: 0.50})
swiss = Ingredient.create({name: 'Swiss' , category: 'cheese', price: 0.50})
jalapeno_monterey_jack = Ingredient.create({name: 'Jalapeño Monterey Jack', category: 'cheese', price: 0.50})
mozzarella = Ingredient.create({name: 'Mozzarella' , category: 'cheese', price: 0.50})
muenster = Ingredient.create({name: 'Muenster' , category: 'cheese', price: 0.50})
provolone = Ingredient.create({name: 'Provolone', category: 'cheese', price: 0.50}) 

brie = Ingredient.create({ name: 'Brie', category: 'cheese', price: 1.25})
crumbled_blue_cheese = Ingredient.create({ name: 'Crumbled Bleu Cheese', category: 'cheese', price: 1.25})
fresh_mozzarella = Ingredient.create({ name: 'Fresh Mozzarella', category: 'cheese', price: 1.25})
smoked_gouda = Ingredient.create({ name: 'Smoked Gouda Cheese', category: 'cheese', price: 1.25})

red_onion = Ingredient.create({name: 'Red Onion', category: 'extra', price: 0})
lettuce = Ingredient.create({name: 'Shredded Lettuce', category: 'extra', price: 0})
tomato = Ingredient.create({name: 'Tomato' , category: 'extra', price: 0})

alfalfa_sprouts = Ingredient.create({name: 'Alfalfa Sprouts', category: 'extra', price: 0.50})
apple = Ingredient.create({name: 'Apple', category: 'extra', price: 0.50})
basil = Ingredient.create({name: 'Basil', category: 'extra', price: 0.50})
olives = Ingredient.create({name: 'Kalamata Olives', category: 'extra', price: 0.50})

capers = Ingredient.create({name: 'Capers' , category: 'extra', price: 1.00})
carrot = Ingredient.create({name: 'Carrot' , category: 'extra', price: 1.00})
coleslaw = Ingredient.create({name: 'Coleslaw', category: 'extra', price: 1.00}) 
cucumber = Ingredient.create({name: 'Cucumber' , category: 'extra', price: 1.00})
grilled_onion = Ingredient.create({name: 'Grilled Onion', category: 'extra', price: 1.00})
grilled_tomato = Ingredient.create({name: 'Grilled Tomato' , category: 'extra', price: 1.00})
horseradish = Ingredient.create({name: 'Horseradish' , category: 'extra', price: 1.00})
hot_peppers = Ingredient.create({name: 'Hot Peppers', category: 'extra', price: 1.00}) 
roasted_red_peppers = Ingredient.create({name: 'Roasted Red Peppers', category: 'extra', price: 1.00})
green_leaf_lettuce = Ingredient.create({name: 'Green Leaf Lettuce' , category: 'extra', price: 1.00}) 
romaine_lettuce = Ingredient.create({name: 'Romaine Lettuce', category: 'extra', price: 1.00})
sauerkraut = Ingredient.create({name: 'Sauerkraut' , category: 'extra', price: 1.00})
shredded_red_cabbage = Ingredient.create({name: 'Shredded Red Cabbage', category: 'extra', price: 1.00})
sliced_pickles = Ingredient.create({name: 'Sliced Pickles', category: 'extra', price: 1.00}) 
sweet_peppers = Ingredient.create({name: 'Sweet Peppers', category: 'extra', price: 1.00})
mushroom = Ingredient.create({name: 'Mushroom', category: 'extra', price: 1.00})
hummus = Ingredient.create({name: 'Hummus', category: 'extra', price: 1.00})

sundried_tomato = Ingredient.create({name: 'Sundried Tomato', category: 'extra', price: 2.00})
sliced_avacado = Ingredient.create({name: 'Sliced Avacado', category: 'extra', price: 2.00})
portobello_mushroom = Ingredient.create({name: 'Portobello Mushroom', category: 'extra', price: 2.00})

bacon = Ingredient.create({name: 'bacon', category: 'extra', price: 2.25})
turkey_bacon = Ingredient.create({name: 'turkey_bacon', category: 'extra', price: 2.25})

house = Ingredient.create({name: "House Vinaigrette", category: 'dressing', price: 0})
asian_sesame_ginger = Ingredient.create({name: "Asian Sesame Ginger", category: 'dressing', price: 0})
greek = Ingredient.create({name: "Greek", category: 'dressing', price: 0})
balsamic = Ingredient.create({name: "Balsamic Vinaigrette",  category: 'dressing', price: 0})
honey_balsamic = Ingredient.create({name: "Honey Balsamic", category: 'dressing', price: 0})
balsamic_vinegar = Ingredient.create({name: "Balsamic Vinegar", category: 'dressing', price: 0}) 
caesar = Ingredient.create({name: "Caesar", category: 'dressing', price: 0})
chipotle_ranch = Ingredient.create({name: "Chipotle Ranch", category: 'dressing', price: 0})
creamy_ranch = Ingredient.create({name: "Creamy Ranch", category: 'dressing', price: 0})
low_fat_caesar = Ingredient.create({name: "Low Fat Caesar", category: 'dressing', price: 0})
honey_mustard = Ingredient.create({name: "Honey Mustard", category: 'dressing', price: 0})
low_fat_honey_mustard = Ingredient.create({name: "Low Fat Honey Mustard", category: 'dressing', price: 0})
italian_dressing = Ingredient.create({name: "Italian", category: 'dressing', price: 0})
fat_free_italian = Ingredient.create({name: "Fat Free Italian", category: 'dressing', price: 0})
oil_n_vinegar = Ingredient.create({name: "Oil & Vinegar", category: 'dressing', price: 0})
fat_free_rasberry_vinagrette = Ingredient.create({name: "Fat Free Raspberry Vinaigrette", category: 'dressing', price: 0})
olive_oil = Ingredient.create({name: "Olive Oil", category: 'dressing', price: 0})
red_wine_vinegar = Ingredient.create({name: "Red Wine Vinegar", category: 'dressing', price: 0})
russian = Ingredient.create({name: "Russian", category: 'dressing', price: 0})
mayo = Ingredient.create({name: "Mayo", category: 'dressing', price: 0})
cream_cheese = Ingredient.create({name: 'Cream Cheese', category: 'dressing', price: 0})
tabasco = Ingredient.create({name: "Tabasco Sauce", category: 'dressing', price: 0})
honeyBBQ_sauce = Ingredient.create({name: 'Honey BBQ Sauce', category: 'dressing', price: 0})
dijon = Ingredient.create({name: 'Dijon Mustard', category: 'dressing', price: 0})


sandwiched = Sandwich.create({name:'Sandwiched', category: 'All-Time-Favorites', price: 10.75})
sandwiched1 = SandwichIngredient.create({sandwich: sandwiched, ingredient: pastrami})
sandwiched2 = SandwichIngredient.create({sandwich: sandwiched, ingredient: corned_beef})
sandwiched3 = SandwichIngredient.create({sandwich: sandwiched, ingredient: coleslaw})
sandwiched4 = SandwichIngredient.create({sandwich: sandwiched, ingredient: russian})

italian = Sandwich.create({name: 'Italian', category: 'All-Time-Favorites', price: 10.75})
italian1 = SandwichIngredient.create({sandwich: italian, ingredient: genoa_salami})
italian2 = SandwichIngredient.create({sandwich: italian, ingredient: capicola})
italian3 = SandwichIngredient.create({sandwich: italian, ingredient: provolone})
italian4 = SandwichIngredient.create({sandwich: italian, ingredient: american})
italian5 = SandwichIngredient.create({sandwich: italian, ingredient: lettuce})
italian6 = SandwichIngredient.create({sandwich: italian, ingredient: tomato})
italian7 = SandwichIngredient.create({sandwich: italian, ingredient: red_onion})
italian8 = SandwichIngredient.create({sandwich: italian, ingredient: hot_peppers})
italian9 = SandwichIngredient.create({sandwich: italian, ingredient: oil_n_vinegar})

american_sandwich = Sandwich.create({name: 'American', category: 'All-Time-Favorites', price: 10.75})
american1 = SandwichIngredient.create({sandwich: italian, ingredient: ham})
american2 = SandwichIngredient.create({sandwich: italian, ingredient: smoked_ham})
american3 = SandwichIngredient.create({sandwich: italian, ingredient: american})
american4 = SandwichIngredient.create({sandwich: italian, ingredient: lettuce})
american5 = SandwichIngredient.create({sandwich: italian, ingredient: tomato})
american6 = SandwichIngredient.create({sandwich: italian, ingredient: mayo})

jimmyT = Sandwich.create({name: 'Jimmy T', category: 'All-Time-Favorites', price: 10.75})
jimmyT1 = SandwichIngredient.create({sandwich: jimmyT, ingredient: chicken_cutlet})
jimmyT2 = SandwichIngredient.create({sandwich: jimmyT, ingredient: mozzarella})
jimmyT3 = SandwichIngredient.create({sandwich: jimmyT, ingredient: grilled_onion})
jimmyT4 = SandwichIngredient.create({sandwich: jimmyT, ingredient: sweet_peppers})
jimmyT5 = SandwichIngredient.create({sandwich: jimmyT, ingredient: honey_mustard})

emmas = Sandwich.create({name: "Emmas's", category: 'All-Time-Favorites', price: 10.75})
emmas1 = SandwichIngredient.create({sandwich: emmas, ingredient: smoked_ham})
emmas2 = SandwichIngredient.create({sandwich: emmas, ingredient: smoked_turkey})
emmas3 = SandwichIngredient.create({sandwich: emmas, ingredient: swiss})
emmas4 = SandwichIngredient.create({sandwich: emmas, ingredient: coleslaw})
emmas5 = SandwichIngredient.create({sandwich: emmas, ingredient: russian})

mikey = Sandwich.create({name: "Mikey's", category: 'All-Time-Favorites', price: 10.75})
mikey1 = SandwichIngredient.create({sandwich: mikey, ingredient: grilled_steak})
mikey2 = SandwichIngredient.create({sandwich: mikey, ingredient: american})
mikey3 = SandwichIngredient.create({sandwich: mikey, ingredient: lettuce})
mikey4 = SandwichIngredient.create({sandwich: mikey, ingredient: tomato})
mikey5 = SandwichIngredient.create({sandwich: mikey, ingredient: grilled_onion})
mikey6 = SandwichIngredient.create({sandwich: mikey, ingredient: mayo})


novie = Sandwich.create({name: 'Novie', category: 'All-Time-Favorites', price: 10.75})
novie1 = SandwichIngredient.create({sandwich: novie, ingredient: smoked_nova})
novie2 = SandwichIngredient.create({sandwich: novie, ingredient: cream_cheese})
novie3 = SandwichIngredient.create({sandwich: novie, ingredient: tomato})
novie4 = SandwichIngredient.create({sandwich: novie, ingredient: red_onion})

tc = Sandwich.create({name: 'TC', category: 'All-Time-Favorites', price: 10.75})
tc1 = SandwichIngredient.create({sandwich: tc, ingredient: turkey})
tc2 = SandwichIngredient.create({sandwich: tc, ingredient: corned_beef})
tc3 = SandwichIngredient.create({sandwich: tc, ingredient: coleslaw})
tc4 = SandwichIngredient.create({sandwich: tc, ingredient: russian})

vegetarian = Sandwich.create({name: "Vegetarian", category: 'All-Time-Favorites', price: 10.75})
vegetarian1 = SandwichIngredient.create({sandwich: vegetarian, ingredient: avacado})
vegetarian2 = SandwichIngredient.create({sandwich: vegetarian, ingredient: green_leaf_lettuce})
vegetarian3 = SandwichIngredient.create({sandwich: vegetarian, ingredient: tomato})
vegetarian4 = SandwichIngredient.create({sandwich: vegetarian, ingredient: carrot})
vegetarian5 = SandwichIngredient.create({sandwich: vegetarian, ingredient: cucumber})
vegetarian6 = SandwichIngredient.create({sandwich: vegetarian, ingredient: alfalfa_sprouts})
vegetarian7 = SandwichIngredient.create({sandwich: vegetarian, ingredient: shredded_red_cabbage})
vegetarian8 = SandwichIngredient.create({sandwich: vegetarian, ingredient: sweet_peppers})
vegetarian9 = SandwichIngredient.create({sandwich: vegetarian, ingredient: honey_mustard})


chickavo = Sandwich.create({name: 'Chickavo', category: 'Grilled Chicken', price: 10.75})
chickavo1 = SandwichIngredient.create({sandwich: chickavo, ingredient: avacado})
chickavo2 = SandwichIngredient.create({sandwich: chickavo, ingredient: roasted_red_peppers})
chickavo3 = SandwichIngredient.create({sandwich: chickavo, ingredient: creamy_ranch})
chickavo4 = SandwichIngredient.create({sandwich: chickavo, ingredient: grilled_chicken_breast})

classic = Sandwich.create({name: 'Classic', category: 'Grilled Chicken', price: 10.75})
classic1 = SandwichIngredient.create({sandwich: classic, ingredient: grilled_chicken_breast})
classic2 =  SandwichIngredient.create({sandwich: classic, ingredient: mozzarella})
classic3 =  SandwichIngredient.create({sandwich: classic, ingredient: grilled_onion})
classic4 =  SandwichIngredient.create({sandwich: classic, ingredient: green_leaf_lettuce})
classic5 =  SandwichIngredient.create({sandwich: classic, ingredient: hot_peppers})
classic6 =  SandwichIngredient.create({sandwich: classic, ingredient: tabasco})

spicy_chicken = Sandwich.create({name: 'Spicy Chicken', category: 'Grilled Chicken', price: 10.75})
spicy_chicken1 =  SandwichIngredient.create({sandwich: spicy_chicken, ingredient: grilled_chicken_breast})
spicy_chicken2 =  SandwichIngredient.create({sandwich: spicy_chicken, ingredient: grilled_onion})
spicy_chicken3 = SandwichIngredient.create({sandwich: spicy_chicken, ingredient: green_leaf_lettuce})
spicy_chicken4 =  SandwichIngredient.create({sandwich: spicy_chicken, ingredient: hot_peppers})
spicy_chicken5 =  SandwichIngredient.create({sandwich: spicy_chicken, ingredient: tabasco})

honeyBBQ = Sandwich.create({name: 'Honey BBQ', category: 'Grilled Chicken', price: 10.75})
honeyBBQ1 = SandwichIngredient.create({sandwich: honeyBBQ, ingredient: grilled_chicken_breast})
honeyBBQ2 =  SandwichIngredient.create({sandwich: honeyBBQ, ingredient: fresh_mozzarella})
honeyBBQ3 =  SandwichIngredient.create({sandwich: honeyBBQ, ingredient: grilled_onion})
honeyBBQ4 =  SandwichIngredient.create({sandwich: honeyBBQ, ingredient: green_leaf_lettuce})
honeyBBQ5 =  SandwichIngredient.create({sandwich: honeyBBQ, ingredient: tomato})
honeyBBQ6 = SandwichIngredient.create({sandwich: honeyBBQ, ingredient: honeyBBQ_sauce})

chicken_cheddar = Sandwich.create({name: 'Chicken Cheddar ', category: 'Breaded Chicken', price: 10.75})
chicken_cheddar1 = SandwichIngredient.create({sandwich: chicken_cheddar, ingredient: chicken_cutlet})
chicken_cheddar2 = SandwichIngredient.create({sandwich: chicken_cheddar, ingredient:cheddar})
chicken_cheddar3 = SandwichIngredient.create({sandwich: chicken_cheddar, ingredient: bacon})
chicken_cheddar4 = SandwichIngredient.create({sandwich: chicken_cheddar, ingredient: lettuce})
chicken_cheddar5 = SandwichIngredient.create({sandwich: chicken_cheddar, ingredient: tomato})


bello_melt = Sandwich.create({name: 'Bello Melt', category: "Chef's Selection", price: 10.75})
bello_melt1 = SandwichIngredient.create({sandwich: bello_melt, ingredient: portobello_mushroom})
bello_melt2 = SandwichIngredient.create({sandwich: bello_melt, ingredient: grilled_onion})
bello_melt3 = SandwichIngredient.create({sandwich: bello_melt, ingredient: mozzarella})
bello_melt4 = SandwichIngredient.create({sandwich: bello_melt, ingredient: basil})
bello_melt5 = SandwichIngredient.create({sandwich: bello_melt, ingredient: roasted_red_peppers})
bello_melt6 = SandwichIngredient.create({sandwich: bello_melt, ingredient: honey_balsamic})

caprese = Sandwich.create({name: 'Caprese', category: "Chef's Selection", price: 10.75})
caprese1 = SandwichIngredient.create({sandwich: caprese, ingredient: fresh_mozzarella})
caprese2 = SandwichIngredient.create({sandwich: caprese, ingredient: roasted_red_peppers})
caprese3 = SandwichIngredient.create({sandwich: caprese, ingredient: tomato})
caprese4 = SandwichIngredient.create({sandwich: caprese, ingredient: basil})
caprese5 = SandwichIngredient.create({sandwich: caprese, ingredient: capers})
caprese6 = SandwichIngredient.create({sandwich: caprese, ingredient: sundried_tomato})

farmhouse_chicken_salad = Sandwich.create({name: "Farmhouse Chicken Salad", category: "Chef's Selection", price: 10.75})
farmhouse_chicken_salad1 = SandwichIngredient.create({sandwich: farmhouse_chicken_salad, ingredient: chicken_salad})
farmhouse_chicken_salad2 = SandwichIngredient.create({sandwich: farmhouse_chicken_salad, ingredient: cucumber})
farmhouse_chicken_salad3 = SandwichIngredient.create({sandwich: farmhouse_chicken_salad, ingredient: shredded_red_cabbage})
farmhouse_chicken_salad4 = SandwichIngredient.create({sandwich: farmhouse_chicken_salad, ingredient: green_leaf_lettuce})
farmhouse_chicken_salad5 = SandwichIngredient.create({sandwich: farmhouse_chicken_salad, ingredient: tomato})

chicken_salad_club = Sandwich.create({name: 'Chicken Salad Club', category: "Chef's Selection", price: 10.75})
chicken_salad_club1 = SandwichIngredient.create({sandwich: chicken_salad_club, ingredient: chicken_salad})
chicken_salad_club2 = SandwichIngredient.create({sandwich: chicken_salad_club, ingredient: bacon})
chicken_salad_club3 = SandwichIngredient.create({sandwich: chicken_salad_club, ingredient: green_leaf_lettuce})
chicken_salad_club4 = SandwichIngredient.create({sandwich: chicken_salad_club, ingredient: tomato})


fishwich = Sandwich.create({name: "Fish'wich", category: 'Fish', price: 10.75})
fishwich1 = SandwichIngredient.create({sandwich: fishwich, ingredient: cod_fish})
fishwich2 = SandwichIngredient.create({sandwich: fishwich, ingredient: coleslaw})
fishwich3 = SandwichIngredient.create({sandwich: fishwich, ingredient: sliced_pickles})
fishwich4 = SandwichIngredient.create({sandwich: fishwich, ingredient: lettuce})
fishwich5 = SandwichIngredient.create({sandwich: fishwich, ingredient: tomato})

tuna_sandwich = Sandwich.create({name: 'Tuna Dijon', category: 'Fish', price: 10.75})
tuna_sandwich1 = SandwichIngredient.create({sandwich: tuna_sandwich, ingredient: tuna})
tuna_sandwich2 = SandwichIngredient.create({sandwich: tuna_sandwich, ingredient: carrot})
tuna_sandwich3 = SandwichIngredient.create({sandwich: tuna_sandwich, ingredient: cucumber})
tuna_sandwich4 = SandwichIngredient.create({sandwich: tuna_sandwich, ingredient: alfalfa_sprouts})
tuna_sandwich5 = SandwichIngredient.create({sandwich: tuna_sandwich, ingredient: tomato})
tuna_sandwich6 = SandwichIngredient.create({sandwich: tuna_sandwich, ingredient: dijon})

# # # spicy_tuna = Sandwich.create({name: 'Spicy Tuna', category: 'Fish', price: 10.75})
# # # spicy_tuna1 = SandwichIngredient.create({sandwich: spicy_tuna.id, ingredient: 

# # # thanksgiving = Sandwich.create({name: 'Thanksgiving', category: 'Gourmet Turkey', price: 10.75})
# # # thanksgiving1 = SandwichIngredient.create({sandwich: thanksgiving.id, ingredient: turkey.id})
# # # thanksgiving2 = SandwichIngredient.create({sandwich: thanksgiving.id, ingredient: stuff

turkey_brie = Sandwich.create({name: 'Turkey Brie', category: 'Gourmet Turkey', price: 10.75})
turkey_brie1 = SandwichIngredient.create({sandwich: turkey_brie, ingredient: smoked_turkey})
turkey_brie2 = SandwichIngredient.create({sandwich: turkey_brie, ingredient: brie})
turkey_brie3 = SandwichIngredient.create({sandwich: turkey_brie, ingredient: green_leaf_lettuce})
turkey_brie4 = SandwichIngredient.create({sandwich: turkey_brie, ingredient: honey_mustard})

crack_jack_turkey = Sandwich.create({name: 'Crack Jack Turkey', category: 'Gourmet Turkey', price: 10.75})
crack_jack_turkey1 = SandwichIngredient.create({sandwich: crack_jack_turkey, ingredient: turkey_pastrami})
crack_jack_turkey2 = SandwichIngredient.create({sandwich: crack_jack_turkey, ingredient: pastrami})
crack_jack_turkey3 = SandwichIngredient.create({sandwich: crack_jack_turkey, ingredient: lettuce})
crack_jack_turkey4 = SandwichIngredient.create({sandwich: crack_jack_turkey, ingredient: tomato})
crack_jack_turkey5 = SandwichIngredient.create({sandwich: crack_jack_turkey, ingredient: jalapeno_monterey_jack})
crack_jack_turkey6 = SandwichIngredient.create({sandwich: crack_jack_turkey, ingredient: red_onion})


steakwich = Sandwich.create({name: "Steak'wich", category: 'Grilled Steak', price: 10.75})
steakwich1 = SandwichIngredient.create({sandwich: steakwich, ingredient: grilled_steak})
steakwich2 = SandwichIngredient.create({sandwich: steakwich, ingredient: provolone})
steakwich3 = SandwichIngredient.create({sandwich: steakwich, ingredient: hot_peppers})
steakwich4 = SandwichIngredient.create({sandwich: steakwich, ingredient: grilled_onion})

big_daddy = Sandwich.create({name: "The Big Daddy", category: 'Grilled Steak', price: 10.75})
big_daddy1 = SandwichIngredient.create({sandwich: big_daddy, ingredient: grilled_steak})
big_daddy2 = SandwichIngredient.create({sandwich: big_daddy, ingredient: avacado})
big_daddy3 = SandwichIngredient.create({sandwich: big_daddy, ingredient: fresh_mozzarella})
big_daddy4 = SandwichIngredient.create({sandwich: big_daddy, ingredient: grilled_onion})
big_daddy5 = SandwichIngredient.create({sandwich: big_daddy, ingredient: roasted_red_peppers})
big_daddy6 = SandwichIngredient.create({sandwich: big_daddy, ingredient: tabasco})

bbqGoudness = Sandwich.create({name: "BBQ Goudness", category: 'Grilled Steak', price: 10.75})
bbqGoudness1 = SandwichIngredient.create({sandwich: bbqGoudness, ingredient: grilled_steak})
bbqGoudness2 = SandwichIngredient.create({sandwich: bbqGoudness, ingredient: smoked_gouda})
bbqGoudness3 = SandwichIngredient.create({sandwich: bbqGoudness, ingredient: green_leaf_lettuce})
bbqGoudness4 = SandwichIngredient.create({sandwich: bbqGoudness, ingredient: mushroom}) 
bbqGoudness5 = SandwichIngredient.create({sandwich: bbqGoudness, ingredient: grilled_onion})
bbqGoudness6 = SandwichIngredient.create({sandwich: bbqGoudness, ingredient: chipotle_ranch})

smi = User.create({first_name: "Eugenia", last_name: 'Kim', email: 'smi@smi.com', password: '123', phone: 1234567890})


